# this workflow checks if the style file compiles using tectonic
name: Compile Check

# this action runs when...
# * a new commit changes the style file or the sample file
# * a new PR changes the style file or the sample file
# * every month
on:
  push:
    branches: [main]
    paths:
      - '**.tex'
      - '**.sty'
  pull_request:
    branches: [main]
    paths:
      - '**.tex'
      - '**.sty'
  schedule:
    - cron: "0 0 1 * *"

jobs:
  # compiles the sample file that uses the style file
  compile:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Compile LateX
        uses: vinay0410/tectonic-action@master
        with:
          # Path of Tex File
          tex_path: sample.tex
          # String stating whether to push output PDF, PDF will only be pushed in case of "yes"
          push: no
