# this workflow checks if the style file compiles using tectonic
name: Compile Check

on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 1 * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v27
      # tectonic
      - name: check textonic (xelatex)
        run: nix shell "nixpkgs#tectonic" -L -c tectonic sample-xelatex.tex

      # platex
      - name: check platex
        run: |
          nix shell "nixpkgs#texliveFull" -L -c platex sample-platex.tex
          nix shell "nixpkgs#texliveFull" -L -c dvipdfmx sample-platex.dvi

      - uses: actions/upload-artifact@v4
        with:
          name: pdf-artifact
          path: sample*.pdf

