# this workflow checks if the style file compiles using tectonic
name: Compile Check

on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 1 * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - uses: cachix/install-nix-action@630ae543ea3a38a9a4166f03376c02c50f408342 # v31.11.0
      # tectonic
      - name: check textonic (xelatex)
        run: nix shell --quiet -L "nixpkgs#tectonic" -c tectonic sample-xelatex.tex

      # platex
      - name: check platex
        run: |
          nix shell --quiet -L "nixpkgs#texliveFull" -c platex sample-platex.tex
          nix shell --quiet -L "nixpkgs#texliveFull" -c dvipdfmx sample-platex.dvi

      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: pdf-artifact
          path: sample*.pdf

